# Generated by Django 3.0.6 on 2020-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0012_auto_20200507_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='matomo_site_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
