# Generated by Django 3.0.7 on 2020-06-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0014_auto_20200616_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('mobile_number', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=1000)),
            ],
        ),
    ]
