# Generated by Django 3.0.7 on 2020-06-16 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0017_contactdetail_live_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
