# Generated by Django 3.0.7 on 2020-06-16 19:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0018_contactdetail_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
