# Generated by Django 3.0.7 on 2020-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0019_auto_20200616_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='img_src',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
