# Generated by Django 3.0.6 on 2020-12-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0021_livestream_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='livestream',
            name='pleroma_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='livestream',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='livestream',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='livestream',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
