# Generated by Django 3.0.6 on 2020-12-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0022_auto_20201223_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='icon_redirect_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
