# Generated by Django 3.0.6 on 2020-05-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveStreamTheme',
            new_name='LiveStream',
        ),
    ]
