# Generated by Django 3.0.6 on 2020-05-07 12:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0002_auto_20200507_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='img_src',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='liveStream/static/images/')),
        ),
    ]
