# Generated by Django 3.0.6 on 2020-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0005_auto_20200507_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='img_src',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
