# Generated by Django 3.0.7 on 2020-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0013_livestream_matomo_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='collect_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestream',
            name='promote_to_frontpage',
            field=models.BooleanField(default=False),
        ),
    ]
