# Generated by Django 3.0.7 on 2020-06-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0015_contactdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetails',
            new_name='ContactDetail',
        ),
    ]
