# Generated by Django 3.0.7 on 2020-06-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0016_auto_20200616_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='live_stream',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='liveStream.LiveStream'),
            preserve_default=False,
        ),
    ]
