# Generated by Django 3.0.7 on 2020-06-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0020_auto_20200616_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='icon_url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
