# Generated by Django 3.0.6 on 2021-03-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0024_livestream_enable_social_media_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
