# Generated by Django 3.0.6 on 2021-09-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0026_auto_20210906_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetailfdp',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contactdetailfdp',
            name='place',
        ),
        migrations.AddField(
            model_name='contactdetailfdp',
            name='country_of_the_institute',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetailfdp',
            name='department',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetailfdp',
            name='institute',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetailfdp',
            name='state_of_the_institute',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
