# Generated by Django 3.0.6 on 2021-09-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0027_auto_20210906_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetailfdp',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactdetailfdp',
            name='country_of_the_institute',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetailfdp',
            name='department',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetailfdp',
            name='email_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactdetailfdp',
            name='institute',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetailfdp',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactdetailfdp',
            name='state_of_the_institute',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
