# Generated by Django 3.0.6 on 2021-09-06 05:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0028_auto_20210906_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetailfdp',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
